import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import AddNewMessage from "../components/AddNewMessage";
import MessagesList from "../components/MessagesList";
import logo from "../public/favicon.png";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [reloadData, setReloadData] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Picciotto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <nav className={styles.nav}>
        <Image src={logo} width="50" height="50" />
        <h1>Picciotto!</h1>
      </nav>

      <main className={styles.main}>
        <AddNewMessage reloadData={reloadData} setReloadData={setReloadData} />
        <MessagesList reloadData={reloadData} setReloadData={setReloadData} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
